name: mapplot
channels:
  - conda-forge

dependencies:
  - conda-build
  - ipykernel
  - jupyterlab
  - ipywidgets
  - matplotlib
  - pandas
  - numpy
  - seaborn
  - plotly
  - cufflinks 

  - pytest
  - pytest-cov
  - python=3.8
  - pip






