name: mapplot
channels:
  - conda-forge

dependencies:
  - conda-build
  - ipykernel
  - jupyterlab
  - ipywidgets
  - matplotlib
  - geopandas
  - pandas
  - numpy
  - seaborn
  - plotly
  - shapely
  - dash
  - dash-core-components
  - dash-html-components
  - dash-renderer

  - pytest
  - pytest-cov
  - python=3.8
  - pip






